# Generated by Django 5.0.6 on 2024-05-11 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cbookapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.CharField(max_length=100, verbose_name="Автор рецепта"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cbookapp.categories",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_steps",
            field=models.TextField(verbose_name="Этапы приготовления"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.CharField(
                max_length=15, verbose_name="Время приготовления, мин."
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="img_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/products/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(verbose_name="Ингредиенты"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название блюда"),
        ),
    ]
