# Generated by Django 5.0.6 on 2024-05-12 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cbookapp", "0002_alter_recipe_author_alter_recipe_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categories",
            old_name="name_category",
            new_name="name",
        ),
    ]
