# Generated by Django 5.0.6 on 2024-05-12 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cbookapp", "0003_rename_name_category_categories_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cbookapp.categories"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_steps",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="img_file",
            field=models.ImageField(blank=True, null=True, upload_to="media/products/"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
